import type { ResearchDefinition } from "./types";

/**
 * Physical mechanisms the environment can validate. This is not an unlock
 * menu exposed to agents: an agent considers a hypothesis only after it has
 * observed the relevant materials and can conduct the test.
 */
export const RESEARCH_CATALOG: readonly ResearchDefinition[] = [
  {
    id: "controlled_fire",
    discoveryName: "Controlled fire",
    hypothesisTemplate: "Dry fiber and wood may sustain useful heat when arranged around stone.",
    survivalEffect: "One wood can produce substantially more warmth and leave a visible fire.",
    inputs: { fiber: 1, wood: 1, stone: 1 },
    prerequisiteTechnologies: [],
    requiredObservations: ["fiber", "wood", "stone"],
    procedure: ["separate dry material", "create friction", "feed the ember", "observe sustained heat"],
    requiredSuccessfulTrials: 2,
    difficulty: 0.47,
  },
  {
    id: "knapped_edge",
    discoveryName: "Knapped stone edge",
    hypothesisTemplate: "Repeated controlled impacts may make a sharper and more useful stone edge.",
    survivalEffect: "Gathering plant, food, and timber resources yields 18% more material.",
    inputs: { stone: 2 },
    prerequisiteTechnologies: [],
    requiredObservations: ["stone"],
    procedure: ["compare stones", "strike at an angle", "inspect the edge", "test cutting ability"],
    requiredSuccessfulTrials: 2,
    difficulty: 0.38,
  },
  {
    id: "twisted_cordage",
    discoveryName: "Twisted cordage",
    hypothesisTemplate: "Twisting several fibers together may produce a stronger binding.",
    survivalEffect: "A shelter requires one fiber instead of two.",
    inputs: { fiber: 2 },
    prerequisiteTechnologies: [],
    requiredObservations: ["fiber"],
    procedure: ["separate fibers", "twist strands", "join opposing twists", "load-test the binding"],
    requiredSuccessfulTrials: 2,
    difficulty: 0.34,
  },
  {
    id: "fired_vessel",
    discoveryName: "Fired clay vessel",
    hypothesisTemplate: "Shaped clay may become a durable container after controlled heating.",
    survivalEffect: "A water collection action carries 0.75 additional units.",
    inputs: { clay: 2, wood: 1 },
    prerequisiteTechnologies: ["controlled_fire"],
    requiredObservations: ["clay", "wood"],
    procedure: ["remove stones from clay", "shape a container", "dry it", "heat it gradually", "test for leaks"],
    requiredSuccessfulTrials: 2,
    difficulty: 0.57,
  },
  {
    id: "water_boiling",
    discoveryName: "Water boiling",
    hypothesisTemplate: "Heating water in a fired vessel may make contaminated water safer.",
    survivalEffect: "With 0.25 wood available, contaminated water is boiled and avoids collection-time health loss.",
    inputs: { freshwater: 1, wood: 1 },
    prerequisiteTechnologies: ["controlled_fire", "fired_vessel"],
    requiredObservations: ["freshwater", "wood"],
    procedure: ["fill the vessel", "heat to a rolling boil", "allow cooling", "compare later effects"],
    requiredSuccessfulTrials: 2,
    difficulty: 0.44,
  },
  {
    id: "food_smoking",
    discoveryName: "Food smoking",
    hypothesisTemplate: "Low heat and smoke may slow food spoilage without burning it.",
    survivalEffect: "A stored food unit restores five additional nutrition points.",
    inputs: { food: 1, wood: 1 },
    prerequisiteTechnologies: ["controlled_fire"],
    requiredObservations: ["food", "wood"],
    procedure: ["prepare food strips", "maintain low smoke", "dry gradually", "compare storage life"],
    requiredSuccessfulTrials: 2,
    difficulty: 0.48,
  },
  {
    id: "herbal_poultice",
    discoveryName: "Herbal poultice",
    hypothesisTemplate: "Prepared local herbs may improve recovery when applied consistently.",
    survivalEffect: "Rest can consume 0.25 herbs to restore one additional health point.",
    inputs: { herbs: 2, freshwater: 1 },
    prerequisiteTechnologies: [],
    requiredObservations: ["herbs", "freshwater"],
    procedure: ["clean the herbs", "crush into a paste", "apply cautiously", "record recovery"],
    requiredSuccessfulTrials: 2,
    difficulty: 0.51,
  },
] as const;
