/** Shared factual method copy for the server and static Pages editions. */
export function DevelopmentMethod() {
  return <>
    <h2>Recurring problems, connected possibilities.</h2>
    <p>Expanded-world studies add a second construction scale: finite vessels, crop beds, protective panels and connected mechanical or electrical components. Water must be deposited or pumped from a real source. Growing food consumes seed reserves, water and time. Wind or heat can drive mechanisms; conductors can convert work, cells store supplied charge, and threshold contacts can regulate a connected system. Losses, leakage, wear and repair remain real costs.</p>
    <p>These are authored, simplified component abilities—not a claim that an agent independently invented a generator from atom-level physics. Short plans are assembled from compatible capabilities and prerequisites. Agents compare those plans with moving, gathering, resting, reusing what exists or doing no optional work. Their personal measurements change contextual expectations; a successful procedure must still execute and pay for every operation when reused.</p>
    <p>Goals can reopen when new experience reveals another recurring problem. A private model is not shared automatically. An agent can voluntarily report an executed procedure or inscribe it on an actual material surface. Another life must encounter and read that surface. Reports keep the original evidence references and are testimony, not additional independent trials or inherited private memory.</p>
    <p>Individual survival remains the default. A separately selected survival-and-discovery motivation permits bounded inquiry only when plausible results could change a decision, with at most eight additional effort units per modeled day. Immediate needs take priority. There is no reward for a building count, named technology, novelty alone or reaching a prescribed era.</p>
    <p>The world supports simplified powered arrangements and relay-style control, not semiconductor fabrication, full chemical engineering, arbitrary software or general-purpose computers. Development is not guaranteed, and a reliable simple strategy can remain the best choice. Existing studies keep their original rules; compatible material-learning studies have an explicit, logged “Enable expanded world” option in Run. It adds no supplies, lives or learned answers.</p>
  </>;
}
